name: Article Ingestion Pipeline

on:
  schedule:
    - cron: "0 1-9/3 * * 1-5" # every 3 hours from 1am-9am UTC, Monday-Friday
  workflow_dispatch:
    # allows you to trigger it manually from GitHub UI

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true 

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    environment: article_ingestion

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: uv sync

      - name: Run batch pipeline
        env:
          ENVIRONMENT: ${{ vars.ENVIRONMENT }}
          STRICT_LLM_FAILURE: "true"
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          LLM_BASE_URL: ${{ vars.LLM_BASE_URL }}
          LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
          LLM_MODEL: ${{ vars.LLM_MODEL }}
        run: uv run python main.py
